/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status?: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a local account (email + password) and sign in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterInput"];
                };
            };
            responses: {
                /** @description Account created, token pair issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                409: components["responses"]["Conflict"];
                /** @description Invalid input */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email + password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginInput"];
                };
            };
            responses: {
                /** @description Token pair issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/dev-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue tokens for an email without Google (local env only)
         * @description Available only when the server runs with app_env=local. Upserts a user by email and returns a token pair. Returns 404 when disabled.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description Token pair issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Google OAuth flow */
        get: {
            parameters: {
                query?: {
                    /** @description Same-site path to land on after login (default /spaces). Carried in the signed OAuth state. Google redirects to the SPA callback route, which then calls /api/v1/auth/google/callback. */
                    redirect_uri?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to Google consent screen */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback */
        get: {
            parameters: {
                query: {
                    code: string;
                    state: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token pair issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new token pair */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refresh_token: string;
                    };
                };
            };
            responses: {
                /** @description New token pair */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenPair"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The authenticated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List spaces the current user belongs to */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Spaces */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Space"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a space */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SpaceInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Space"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{spaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: components["parameters"]["SpaceId"];
            };
            cookie?: never;
        };
        /** Get a space */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    spaceId: components["parameters"]["SpaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Space */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Space"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{spaceId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: components["parameters"]["SpaceId"];
            };
            cookie?: never;
        };
        /** List members of a space */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    spaceId: components["parameters"]["SpaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Members */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpaceMember"][];
                    };
                };
            };
        };
        put?: never;
        /** Add a member by email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    spaceId: components["parameters"]["SpaceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        role?: components["schemas"]["MemberRole"];
                    };
                };
            };
            responses: {
                /** @description Added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpaceMember"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{spaceId}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: components["parameters"]["SpaceId"];
            };
            cookie?: never;
        };
        /** List categories */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    spaceId: components["parameters"]["SpaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categories */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a category */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    spaceId: components["parameters"]["SpaceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Category"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{spaceId}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: components["parameters"]["SpaceId"];
            };
            cookie?: never;
        };
        /** List expenses in a space */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    limit?: number;
                    cursor?: string;
                };
                header?: never;
                path: {
                    spaceId: components["parameters"]["SpaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Expenses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExpenseList"];
                    };
                };
            };
        };
        put?: never;
        /** Record an expense */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    spaceId: components["parameters"]["SpaceId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExpenseInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Expense"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/spaces/{spaceId}/expenses/{expenseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: components["parameters"]["SpaceId"];
                expenseId: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        /** Get an expense */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    spaceId: components["parameters"]["SpaceId"];
                    expenseId: components["parameters"]["ExpenseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Expense */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Expense"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete an expense (soft delete) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    spaceId: components["parameters"]["SpaceId"];
                    expenseId: components["parameters"]["ExpenseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update an expense */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    spaceId: components["parameters"]["SpaceId"];
                    expenseId: components["parameters"]["ExpenseId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExpenseInput"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Expense"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/spaces/{spaceId}/balances": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: components["parameters"]["SpaceId"];
            };
            cookie?: never;
        };
        /** Per-member balance for a space */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    spaceId: components["parameters"]["SpaceId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Balances */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Balance"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** @description Access token lifetime in seconds */
            expires_in: number;
        };
        RegisterInput: {
            /** Format: email */
            email: string;
            password: string;
            name?: string;
        };
        LoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            avatar_url?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        MemberRole: "owner" | "member";
        Space: {
            /** Format: uuid */
            id: string;
            name: string;
            currency: string;
            /** Format: uuid */
            owner_id: string;
            /** Format: date-time */
            created_at: string;
        };
        SpaceInput: {
            name: string;
            /** @default USD */
            currency: string;
        };
        SpaceMember: {
            /** Format: uuid */
            space_id: string;
            /** Format: uuid */
            user_id: string;
            role: components["schemas"]["MemberRole"];
            /** Format: date-time */
            joined_at: string;
            user: components["schemas"]["User"];
        };
        Category: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            space_id: string;
            name: string;
            color?: string | null;
            /** @description Emoji or icon name */
            icon?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        CategoryInput: {
            name: string;
            color?: string;
            icon?: string;
        };
        Expense: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            space_id: string;
            /** Format: uuid */
            payer_id: string;
            /** Format: uuid */
            category_id?: string | null;
            /** @description Amount in minor units */
            amount_cents: number;
            currency: string;
            description?: string | null;
            /** Format: date */
            spent_at: string;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ExpenseInput: {
            /** Format: uuid */
            payer_id: string;
            /** Format: uuid */
            category_id?: string;
            amount_cents: number;
            currency?: string;
            description?: string;
            /** Format: date */
            spent_at: string;
        };
        ExpenseList: {
            items: components["schemas"]["Expense"][];
            next_cursor?: string | null;
        };
        Balance: {
            /** Format: uuid */
            user_id: string;
            /** @description Total this member paid */
            paid_cents: number;
            /** @description This member's equal share of all expenses */
            share_cents: number;
            /** @description paid_cents - share_cents (positive = is owed) */
            net_cents: number;
        };
    };
    responses: {
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The write violates a uniqueness constraint */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        SpaceId: string;
        ExpenseId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
